[default.files]
alacritty = "~/.alacritty.yml"
aliases = "~/.aliases"
gitconfig = "~/.gitconfig"
hyper = "~/.hyper.js"
profile = "~/.profile"
starship = "~/.config/starship.toml"
zellij = "~/.config/zellij/config.yaml"
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"

[default.variables]
