[terminals.files]
alacritty = "~/.config/alacritty/alacritty.yml"
kitty = { target = "~/.config/kitty", type = "symbolic" }

[tools.files]
gitconfig = "~/.gitconfig"
bat = { target = "~/.config/bat", type = "symbolic"}
nvim = { target = "~/.config/nvim", type = "symbolic" }

[shell.files]
aliases = "~/.aliases"
profile = "~/.profile"
starship = "~/.config/starship.toml"
theme = "~/theme.sh"
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"
