[default.files]
alacritty = "~/.config/alacritty/alacritty.yml"
aliases = "~/.aliases"
gitconfig = "~/.gitconfig"
hyper = "~/.hyper.js"
profile = "~/.profile"
starship = "~/.config/starship.toml"
vscode = "~/.vscode/custom.css"
zellij = "~/.config/zellij/config.yaml"
zprofile = "~/.zprofile"
zshrc = "~/.zshrc"

[vim.files]
nvim = { type = "symbolic", target = "~/.config/nvim" }

[default.variables]
